# TRMNLP configuration - LARGE FAMILY (20 children, two-column layout)
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {}

# override variables
variables:
  trmnl: {}

  subject:
    first_name: "Ernest August"
    last_name: "Reyman"
    birth: 1851
    death: 1928
    photo_url: "https://ttop.github.io/trmnl-demo/images/wide.jpg"

  spouse:
    first_name: "Louisa"
    last_name: "Heitt"
    birth: 1857
    death: 1940
    photo_url: "https://ttop.github.io/trmnl-demo/images/tall.jpg"

  subject_parents:
    father:
      first_name: "Johannes"
      last_name: "Reumann"
      birth: 1810
      death: 1881
    mother:
      first_name: "Anna Dorthea"
      last_name: "Schneider"
      birth: 1814
      death: 1875

  spouse_parents:
    father:
      first_name: "Johannes"
      last_name: "Heidt"
      birth: 1831
      death: 1904
    mother:
      first_name: "Louisa"
      last_name: "Malch"
      birth: 1835
      death: null

  children:
    - first:
        first_name: "Roy"
        last_name: "Reyman"
        birth: 1876
        death: 1879
        child: true
    - first:
        first_name: "George William"
        last_name: "Reyman"
        birth: 1878
        death: 1955
        child: true
    - first:
        first_name: "Luella E."
        last_name: "Reyman"
        birth: 1880
        death: 1959
        child: true
    - first:
        first_name: "John Alva"
        last_name: "Reyman"
        birth: 1882
        death: 1952
        child: true
    - first:
        first_name: "Charles Fredrick"
        last_name: "Reyman"
        birth: 1884
        death: 1964
        child: true
    - first:
        first_name: "William George"
        last_name: "Reyman"
        birth: 1887
        death: 1956
        child: true
    - first:
        first_name: "Hattie Estella"
        last_name: "Reyman"
        birth: 1888
        death: 1973
        child: true
    - first:
        first_name: "Loretta Catherine"
        last_name: "Reyman"
        birth: 1890
        death: 1950
        child: true
    - first:
        first_name: "Florence Cora"
        last_name: "Reyman"
        birth: 1891
        death: 1976
        child: true
    - first:
        first_name: "Frank Lewis"
        last_name: "Reyman"
        birth: 1894
        death: 1987
        child: true
    - first:
        first_name: "Ernest Rodney"
        last_name: "Reyman"
        birth: 1899
        death: 1970
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Twelve"
        birth: 1901
        death: 1975
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Thirteen"
        birth: 1903
        death: 1977
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Fourteen"
        birth: 1905
        death: 1979
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Fifteen"
        birth: 1907
        death: 1981
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Sixteen"
        birth: 1909
        death: 1983
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Seventeen"
        birth: 1911
        death: 1985
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Eighteen"
        birth: 1913
        death: 1987
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Nineteen"
        birth: 1915
        death: 1989
        child: true
    - first:
        first_name: "Test Child"
        last_name: "Twenty"
        birth: 1917
        death: 1991
        child: true
