# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {}

# override variables
variables:
  trmnl: {}

  subject:
    name: "Ernest August Reyman"
    birth: 1851
    death: 1928
    photo_url: "https://example.github.io/genealogy/photos/ernest_reyman.jpg"

  spouse:
    name: "Louisa Heitt"
    birth: 1851
    death: 1928
    photo_url: "https://example.github.io/genealogy/photos/louisa_heitt.jpg"

  subject_parents:
    father:
      name: "Johannes Reumann"
      birth: 1810
      death: 1881
    mother:
      name: "Anna Dorthea Schneider"
      birth: 1814
      death: 1875

  spouse_parents:
    father:
      name: "Johannes Heidt"
      birth: 1831
      death: 1904
    mother:
      name: "Louisa Malch"
      birth: 1835
      death: null

  children:
    - name: "Roy Reyman"
      birth: 1876
      death: 1879
      spouse: null
    - name: "George William Reyman"
      birth: 1878
      death: 1955
      spouse: "Lillian Amanda Johnson (1883-1949)"
    - name: "George Volkert"
      birth: 1883
      death: 1941
      spouse: "Luella E. Reyman (1880-1959)"
    - name: "John Alva Reyman"
      birth: 1882
      death: 1952
      spouse: "Lillian Marie Beazley (1889-1990)"
    - name: "Charles Fredrick Reyman"
      birth: 1884
      death: 1964
      spouse: "Eva Juanita Servis (1898-1981)"
    - name: "William George Reyman"
      birth: 1887
      death: 1956
      spouse: "Vera Pearl Servis (1896-1966)"
    - name: "Walter Hugh Joy"
      birth: 1886
      death: 1944
      spouse: "Hattie Estella Reyman (1888-1973)"
    - name: "Loretta Catherine Reyman"
      birth: 1890
      death: 1950
      spouse: null
    - name: "John Mervyn Joy"
      birth: 1891
      death: 1973
      spouse: "Florence Cora Reyman (1891-1976)"
    - name: "Frank Lewis"
      birth: 1894
      death: 1987
      spouse: "Ethel Louise Tuschoff (1908-1946)"
    - name: "Ernest Rodney Reyman"
      birth: 1899
      death: 1970
      spouse: "Lura Ruth Casey (1915-1955)"
