# TRMNLP configuration - SMALL FAMILY (11 children, single column with spouses)
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {}

# override variables
variables:
  trmnl: {}

  subject:
    name: "Ernest August Reyman"
    birth: 1851
    death: 1928
    photo_url: "https://ttop.github.io/trmnl-demo/images/m.jpg"

  spouse:
    name: "Louisa Heitt"
    birth: 1857
    death: 1940
    photo_url: "https://ttop.github.io/trmnl-demo/images/w.jpg"

  subject_parents:
    father:
      name: "Johannes Reumann"
      birth: 1810
      death: 1881
    mother:
      name: "Anna Dorthea Schneider"
      birth: 1814
      death: 1875

  spouse_parents:
    father:
      name: "Johannes Heidt"
      birth: 1831
      death: 1904
    mother:
      name: "Louisa Malch"
      birth: 1835
      death: null

  children:
    - first:
        name: "Roy Reyman"
        birth: 1876
        death: 1879
        child: true
    - first:
        name: "George William Reyman"
        birth: 1878
        death: 1955
        child: true
      second:
        name: "Lillian Amanda Johnson"
        birth: 1883
        death: 1949
    - first:
        name: "George Volkert"
        birth: 1883
        death: 1941
      second:
        name: "Luella E. Reyman"
        birth: 1880
        death: 1959
        child: true
    - first:
        name: "John Alva Reyman"
        birth: 1882
        death: 1952
        child: true
      second:
        name: "Lillian Marie Beazley"
        birth: 1889
        death: 1990
    - first:
        name: "Charles Fredrick Reyman"
        birth: 1884
        death: 1964
        child: true
      second:
        name: "Eva Juanita Servis"
        birth: 1898
        death: 1981
    - first:
        name: "William George Reyman"
        birth: 1887
        death: 1956
        child: true
      second:
        name: "Vera Pearl Servis"
        birth: 1896
        death: 1966
    - first:
        name: "Walter Hugh Joy"
        birth: 1886
        death: 1944
      second:
        name: "Hattie Estella Reyman"
        birth: 1888
        death: 1973
        child: true
    - first:
        name: "Loretta Catherine Reyman"
        birth: 1890
        death: 1950
        child: true
    - first:
        name: "John Mervyn Joy"
        birth: 1891
        death: 1973
      second:
        name: "Florence Cora Reyman"
        birth: 1891
        death: 1976
        child: true
    - first:
        name: "Frank Lewis Reyman"
        birth: 1894
        death: 1987
        child: true
      second:
        name: "Ethel Louise Tuschoff"
        birth: 1908
        death: 1946
    - first:
        name: "Ernest Rodney Reyman"
        birth: 1899
        death: 1970
        child: true
      second:
        name: "Lura Ruth Casey"
        birth: 1915
        death: 1955
